src/WebApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApp.Services;
using WebApp.ViewModels;

namespace WebApp.Controllers {

    public class AdminController : BaseController {
        public AdminController (IControllerServices services) : base (services) { }

        [Route ("")]
        [Route ("app-link")]
        public async Task<IActionResult> Index () {
            var tagDTO = new TagDTO (
                _context._user.UserName (),
                _context._profile,
                _context._mapper.Map<IEnumerable<TagDTO>> (await _context._tag.GetAllTagActived ()));

            return View (tagDTO);
        }

        [Route ("app-get-link/{username}")]
        public async Task<IActionResult> RenderLinksUserPartial (string username) {
            var tagDTO = new TagDTO (
                username,
                _context._profile,
                _context._mapper.Map<IEnumerable<TagDTO>> (await _context._tag.GetAllTagActived ()));

            return ViewComponent ("RenderLinksUser", tagDTO);
        }

        [Route ("app-get-link-adm")]
        public async Task<IActionResult> RenderLinksUserPartial () {
            var tagDTO = new TagDTO (
                _context._user.UserName (),
                _context._profile,
                _context._mapper.Map<IEnumerable<TagDTO>> (await _context._tag.GetAllTagActived ()));

            return ViewComponent ("RenderLinksAdmUser", tagDTO);
        }

        [Route ("app-create-link")]
        public async Task<JsonResult> Create (TagDTO tagDTO) {

            await _context._tag.Add (_context._mapper.Map<Tag> (tagDTO));

            return Json (new {
                success = OperacaoValida (),
                    data = tagDTO,
                    username = _context._user.UserName ()
            });
        }

        [Route ("app-update-link")]
        public async Task<JsonResult> Update (TagDTO tagDTO) {

            //prevent null columns....
            var dataObj = await _context._tag.GetOne (a => a.Id == tagDTO.Id);
            dataObj.Name = tagDTO.Name;
            dataObj.TargetLink = tagDTO.TargetLink;
            dataObj.Active = tagDTO.Active;
            await _context._tag.Update (dataObj);

            return Json (new {
                success = OperacaoValida (),
                    data = tagDTO,
                    username = _context._user.UserName ()
            });
        }

        [AllowAnonymous]
        // [Route ("p/{username?}")]
        [Route ("/{username?}")]
        public async Task<IActionResult> Profile (string username) {

            var tagDTO = new TagDTO (
                username,
                _context._profile,
                _context._mapper.Map<IEnumerable<TagDTO>> (await _context._tag.GetAllTagByUserName (username)));

            return View (tagDTO);
        }

        [AllowAnonymous]
        [Route ("app-save-ip-data")]
        public async Task<JsonResult> RegisterIpData (Guid id) {

            var tagDTO = new TagDataDTO (id,
                _context._ipServices.ipFromServer,
                _context._ipServices.userAgent,
                JsonConvert.DeserializeObject<IPDTO> (await _context._ipServices.GetDataFromIp ()));

            var task = _context._tagData.Add (_context._mapper.Map<TagData> (tagDTO));

            return Json (new {
                success = OperacaoValida ()
            });
        }

    }
}

src/WebApp/ViewComponents/RenderLinksAdmUserViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApp.Services;
using WebApp.ViewModels;

namespace WebApp.Extensions {

    public class RenderLinksAdmUserViewComponent : ViewComponent {

        private IControllerServices _services;

        public RenderLinksAdmUserViewComponent (IControllerServices services) {
            this._services = services;
        }

        public async Task<IViewComponentResult> InvokeAsync () {

            var tagDTO = new TagDTO (
                _services._user.UserName (),
                _services._profile,
                _services._mapper.Map<IEnumerable<TagDTO>> (await _services._tag.GetAllTagActived ()));

            return View (tagDTO);
        }

    }
}

src/WebApp/ViewComponents/RenderLinksUserViewComponent.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApp.Services;
using WebApp.ViewModels;

namespace WebApp.Extensions {
    public class RenderLinksUserViewComponent : ViewComponent {

        private IControllerServices _services;

        public RenderLinksUserViewComponent (IControllerServices services) {
            this._services = services;
        }

        public async Task<IViewComponentResult> InvokeAsync (string username) {

            var tagDTO = new TagDTO (
                username ?? _services._user.UserName (),
                _services._profile,
                _services._mapper.Map<IEnumerable<TagDTO>> (await _services._tag.GetAllTagActived ()));

            return View (tagDTO);
        }
    }

}

src/WebApp/Views/Admin/Index.cshtml
@model TagDTO


<form asp-antiforgery="true" >  </form> 
 <input type="hidden" asp-for="TotalTags">

<input type="hidden" id="url" value=@Url.Action("Update", "Admin")>
 
<div class="admin-link">
        <div class="add-link">
            <div class="card rounded-0">
                <div class="card-block form-add">
                    <input class="form-control form-control-md g-rounded-20"  asp-for="@Model.Name" placeholder="Name"  />
                    <input class="form-control form-control-md g-rounded-20"  asp-for="@Model.TargetLink" placeholder="Url"  />
                    <button class="btn btn-md u-btn-primary g-rounded-20"
                    data-url="@Url.Action("Create", "Admin")" 
                    id="add" 
                    value="Add">Add New Link</button>                
                </div>
            </div>   
                <div class="card rounded-0">
                    <p>Links</p>
                    <div class="links">
                        <vc:render-links-adm-user />
                    </div>
                </div>          
        </div> 
    <div class="view-link">
        <vc:render-links-user username="@User.Identity.Name" />
    </div>
</div>
 
 
@section Scripts
{
    <script>
        SetupCreateLink();
    </script>
}

src/WebApp/Views/Admin/Profile.cshtml
@model TagDTO
<style>
    body {
            background: #fff !important;
    }
</style>


<h1>@Model.Name</h1>
<h1>@Model.Theme</h1>
<h1>@Model.MainLinkImg</h1>

<img id="imgProfile" src="@Model.GetImgConverted" alt="">

 <form asp-antiforgery="true"> </form>

<div class="container">
    <div class="tags">
         <div class="tag">
             <div class="profile-link">
                 @foreach(var item  in @Model.Tags)
                    {
                        <div class="item">
                            <a class="tag-register" 
                               href="@item.TargetLink" 
                               target="_blank" 
                               data-url="@Url.Action("RegisterIpData", "Admin")"
                               rel="noopener noreferrer"
                               data-id="@item.Id">@item.Name</a>
                        </div> 
                    }
            </div>            
         </div>
    </div>
</div>

 

@section Scripts
{
   <script>
       RegisterTag()
   </script>
}