src/WebApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApp.Services;
using WebApp.ViewModels;

namespace WebApp.Controllers {

    public class AdminController : BaseController {
        public AdminController (IControllerServices services) : base (services) { }

        [Route ("")]
        [Route ("app-link")]
        public async Task<IActionResult> Index () {
            var tagDTO = new TagDTO (
                _context._user.UserName (),
                _context._profile,
                _context._mapper.Map<IEnumerable<TagDTO>> (await _context._tag.GetAllTagActived ()));

            return View (tagDTO);
        }

        [Route ("app-get-link/{username}")]
        public async Task<IActionResult> RenderLinksUserPartial (string username) {
            var tagDTO = new TagDTO (
                username,
                _context._profile,
                _context._mapper.Map<IEnumerable<TagDTO>> (await _context._tag.GetAllTagActived ()));

            return ViewComponent ("RenderLinksUser", tagDTO);
        }

        [Route ("app-get-link-adm")]
        public async Task<IActionResult> RenderLinksUserPartial () {
            var tagDTO = new TagDTO (
                _context._user.UserName (),
                _context._profile,
                _context._mapper.Map<IEnumerable<TagDTO>> (await _context._tag.GetAllTagActived ()));

            return ViewComponent ("RenderLinksAdmUser", tagDTO);
        }

        [Route ("app-create-link")]
        public async Task<JsonResult> Create (TagDTO tagDTO) {

            await _context._tag.Add (_context._mapper.Map<Tag> (tagDTO));

            return Json (new {
                success = OperacaoValida (),
                    data = tagDTO,
                    username = _context._user.UserName ()
            });
        }

        [Route ("app-update-link")]
        public async Task<JsonResult> Update (TagDTO tagDTO) {

            //prevent null columns....
            var dataObj = await _context._tag.GetOne (a => a.Id == tagDTO.Id);
            dataObj.Name = tagDTO.Name;
            dataObj.TargetLink = tagDTO.TargetLink;
            dataObj.Active = tagDTO.Active;
            await _context._tag.Update (dataObj);

            return Json (new {
                success = OperacaoValida (),
                    data = tagDTO,
                    username = _context._user.UserName ()
            });
        }

        [AllowAnonymous]
        // [Route ("p/{username?}")]
        [Route ("/{username?}")]
        public async Task<IActionResult> Profile (string username) {

            var tagDTO = new TagDTO (
                username,
                _context._profile,
                _context._mapper.Map<IEnumerable<TagDTO>> (await _context._tag.GetAllTagByUserName (username)));

            return View (tagDTO);
        }

        [AllowAnonymous]
        [Route ("app-save-ip-data")]
        public async Task<JsonResult> RegisterIpData (Guid id) {

            var tagDTO = new TagDataDTO (id,
                _context._ipServices.ipFromServer,
                _context._ipServices.userAgent,
                JsonConvert.DeserializeObject<IPDTO> (await _context._ipServices.GetDataFromIp ()));

            var task = _context._tagData.Add (_context._mapper.Map<TagData> (tagDTO));

            return Json (new {
                success = OperacaoValida ()
            });
        }

    }
}

src/WebApp/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApp.Services;
using WebApp.ViewModels;

namespace WebApp.Controllers {

    public class DashboardController : BaseController {
        public DashboardController (IControllerServices services) : base (services) { }

        [Route ("app-dashboard")]
        public async Task<IActionResult> Dashboard () {
            return View (new Dashboard (
                _context._mapper.Map<IEnumerable<TagDTO>> (await _context._tag.GetAllTagActived ())));
        }

        [Route ("app-data-dashboard/{id?}")]
        public async Task<JsonResult> DashboardData (Guid id, Nullable<DateTime> start, Nullable<DateTime> end) {
            var data = (await GetData (id, start ?? DateTime.MinValue, end ?? DateTime.MaxValue));

            return Json (new {
                data.Id,
                    data.Tag.Name,
                    data.Stats
            });
        }

        private async Task<Dashboard> GetData (Guid id, DateTime start, DateTime end) {
            var dash = new Dashboard (
                _context._mapper.Map<TagDTO> (await _context._tag.GetTagWithAllTagData (id)),
                start,
                end
            );
            return dash;
        }
    }
}

src/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>WebApp - @ViewData["Title"]</title>
    <partial name="_css">
</head>
<body class="has-fixed-sidebar">
    <header>
         @{ Html.RenderPartialIf("_header", User.Identity.IsAuthenticated, "profile;logout"); }
    </header>
    <partial name="_CookieConsentPartial" />
    <main class="container">
    <div class="row no-gutters g-pos-rel g-overflow-x-hidden">
        @RenderBody()
    </div>
    </main>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <partial name="_js">
    @RenderSection("Scripts", required: false)
</body>
</html>

src/WebApp/Views/Shared/_css.cshtml
<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
    asp-fallback-test-class="sr-only" 
    asp-fallback-test-property="position" asp-fallback-test-value="absolute"
    crossorigin="anonymous"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
<script defer src="https://kit.fontawesome.com/e95e051021.js" crossorigin="anonymous"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">

<link rel="stylesheet" href="~/css/unify-core.css">
<link rel="stylesheet" href="~/css/unify-components.css">
<link rel="stylesheet" href="~/css/unify-globals.css"> 


<link rel="stylesheet" href="~/css/site.css" />

src/WebApp/Views/Shared/_header.cshtml
 
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">Links</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <partial name="_LoginPartial" />
            <ul class="navbar-nav flex-grow-1">
                <div id="loading" class="hide spinner-border text-primary" role="status">
                <span class="sr-only">Loading...</span>
            </div>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Dashboard">Metrics</a>
            </li>
                <li class="nav-item">
                <a  class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Settings</a>
            </li>
            </ul>
        </div>
    </div>
</nav> 

src/WebApp/Views/Shared/_js.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
        asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
        asp-fallback-test="window.jQuery"
        crossorigin="anonymous"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
</script>
<script src="~/js/jquery-migrate.min.js"></script>
<script src="~/js/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
        asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
        asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
        crossorigin="anonymous"
        integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
</script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script src="~/js/hs.core.js"></script>





<script src="~/js/site.js"></script>
 

src/WebApp/Views/Shared/_nav.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">WebApp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <partial name="_LoginPartial" />
            <ul class="navbar-nav flex-grow-1">
                
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Tag</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Profile" asp-route-username="shpsyte" >Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Dashboard"  >Dashboard</a>
                </li>
                
            </ul>
        </div>
    </div>
</nav>

src/WebApp/Views/Shared/_sidebar.cshtml
 <!-- Sidebar Nav -->
    <div id="sideNav" class="col-auto u-sidebar-navigation-v1 u-sidebar-navigation--dark">
      <div class="js-custom-scroll u-sidebar-navigation-v1-inner">
        <ul id="sideNavMenu" class="u-sidebar-navigation-v1-menu u-side-nav--top-level-menu g-min-height-100vh mb-0">
          
          <li class="u-sidebar-navigation-v1-menu-item u-side-nav--top-level-menu-item">
              <a class="media u-side-nav--top-level-menu-link u-side-nav--hide-on-hidden g-px-15 g-py-12" asp-area="" 
              asp-controller="Admin" asp-action="Index" >
              <span class="media-body align-self-center">My Links</span>
            </a>
          </li>
           <li class="u-sidebar-navigation-v1-menu-item u-side-nav--top-level-menu-item">
            <a class="media u-side-nav--top-level-menu-link u-side-nav--hide-on-hidden g-px-15 g-py-12"  asp-area="" asp-controller="Dashboard" asp-action="Dashboard" >
              <span class="media-body align-self-center">Metrics</span>
            </a>
          </li>


         <li class="u-sidebar-navigation-v1-menu-item u-side-nav--top-level-menu-item">
              <a class="media u-side-nav--top-level-menu-link u-side-nav--hide-on-hidden g-px-15 g-py-12" target="_blank" asp-area="" 
              asp-controller="Admin" asp-action="Profile" asp-route-username="@User.Identity.Name">
              <span class="media-body align-self-center">My Zlink</span>
            </a>
          </li>
 


          <li class="u-sidebar-navigation-v1-menu-item u-side-nav--top-level-menu-item">
              <a class="media u-side-nav--top-level-menu-link u-side-nav--hide-on-hidden g-px-15 g-py-12"
              asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">
              <span class="media-body align-self-center">My Account</span>
            </a>
          </li>

          <li class="u-sidebar-navigation-v1-menu-item u-side-nav--top-level-menu-item">
             <form  class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button  type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                </form>
          </li>
 
           
 
        </ul>
      </div>
    </div>
    <!-- End Sidebar Nav -->